services:
  whisper-server-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: whisper-server
    volumes:
      - ./volumes/whisper:/data
      - ./volumes/voices:/data/voices
    environment:
      - TZ=Europe/Istanbul
      - VOICES_DIR=/data/voices
      - SPEAKER_THRESHOLD=0.80
      - VOICE_SCAN_INTERVAL=10
      - WHISPER_MODEL=${WHISPER_MODEL:-Systran/faster-whisper-medium}
    restart: unless-stopped
    ports:
      - 10300:10300
      - 8080:8080
    command:
      [
        "--model", "${WHISPER_MODEL:-Systran/faster-whisper-medium}",
        "--beam-size", "5",
        "--language", "tr",
        "--device", "cpu",
        "--compute-type", "int8"
      ]
    profiles:
      - cpu

  whisper-server-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: whisper-server
    volumes:
      - ./volumes/whisper:/data
      - ./volumes/voices:/data/voices
    environment:
      - TZ=Europe/Istanbul
      - VOICES_DIR=/data/voices
      - SPEAKER_THRESHOLD=0.80
      - VOICE_SCAN_INTERVAL=10
      - WHISPER_MODEL=${WHISPER_MODEL:-Systran/faster-whisper-medium}
    restart: unless-stopped
    ports:
      - 10300:10300
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    command:
      [
        "--model", "${WHISPER_MODEL:-Systran/faster-whisper-medium}",
        "--beam-size", "5",
        "--language", "tr",
        "--device", "cuda",
        "--compute-type", "int8"
      ]
    profiles:
      - gpu
